name: Plugin Auto-PR

on:
  push:
    branches:
      - main

jobs:
  auto_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dify Plugin Auto-PR
        uses: langgenius/dify-plugin-action@main
        with:
          github-token: ${{ secrets.PLUGIN_ACTION }}
